#! /bin/sh

pkill sxhkd
sxhkd -m -1 &

MONITOR_NUM=$(xrandr | grep ' connected' | wc -l)

if [ $MONITOR_NUM = 2 ]; then
    bspc monitor DP1 -d 0 1 2 3
    bspc monitor DP2 -d 4 5 6 7
else
    bspc monitor -d 0 1 2 3 4 5 6 7
fi

bspc config border_width         3
bspc config border_radius        10
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_singleton true
bspc config gapless_monocle      true

bspc config active_border_color "#606060"
bspc config focused_border_color "#009F9F"
bspc config normal_border_color "#303030"
bspc config automatic_scheme longest_side

bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

xsetroot -cursor_name left_ptr

fcitx5 &

pkill flameshot; flameshot &

nm-applet &

fix_xcursor &

pkill volumeicon; volumeicon &

nitrogen --restore

xset r rate 180 30

if [ -f ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload -c ~/.config/polybar/config main &
  done
else
  polybar --reload -c ~/.config/polybar/config main &
fi
